name: Automated Testing only

on:
  push

env:
  TAG: SanityCheck.${{ github.event.pusher.name }}.${{ github.event.repository.updated_at}}

jobs:
  run_Tests_UAT:
    needs: deploy_UAT
    name: Run_Tests_UAT
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: cerberus-action
      uses: cerberustesting/cerberus-github-action@v6
      with:
        host: https://jftl.cerberus-testing.com
        campaign: SanityCheck
        apikey: ${{ secrets.APIKEY }}
        author: ${{ github.event.pusher.name }}
        environment: UAT
        tag: ${TAG}
